-- Consistent Blood Bank Insertions
BEGIN
    BEGIN INSERT INTO BLOOD_BANK VALUES (1, 101, 0, 'Red Cross Central Blood Bank'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
    BEGIN INSERT INTO BLOOD_BANK VALUES (2, 102, 0, 'Apollo Hospital Blood Center'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
    BEGIN INSERT INTO BLOOD_BANK VALUES (3, 103, 0, 'LifeCare Blood Bank'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
    BEGIN INSERT INTO BLOOD_BANK VALUES (4, 104, 0, 'Medanta Blood Collection Unit'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
    BEGIN INSERT INTO BLOOD_BANK VALUES (5, 105, 0, 'Narayana Health Blood Bank'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
    BEGIN INSERT INTO BLOOD_BANK VALUES (6, 106, 0, 'Sunrise Blood Bank'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
    BEGIN INSERT INTO BLOOD_BANK VALUES (7, 107, 0, 'Holy Family Blood Center'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
    BEGIN INSERT INTO BLOOD_BANK VALUES (8, 108, 0, 'Unity Blood Bank'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
END;
/